add support for droidspaces

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -126,6 +126,16 @@ on:
           - 4.19
           - 5.4
 
+      droidspaces:
+        description: "DroidSpaces: Enable DroidSpaces"
+        required: true
+        type: choice
+        default: None
+        options:
+          - None
+          - 5.4-6.6
+          - 3.18-4.19
+
       has_modules_repo:
         description: "Has-Modules-Repo: Enable this ur kernel has modules repo"
         required: true
@@ -200,21 +210,21 @@ jobs:
         run: |
           if [[ "${{ inputs.kernel_source }}" == "Manual-Type" ]]; then
 
-            git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source_manual }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}.git ${{ inputs.soc }}
+            git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source_manual }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}.git ${{ inputs.soc }} || exit 1
 
             if [[ "${{ inputs.has_modules_repo }}" == "true" ]]; then
 
-              git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source_manual }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}-modules.git ${{ inputs.soc }}-modules
+              git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source_manual }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}-modules.git ${{ inputs.soc }}-modules || exit 1
 
             fi
 
           else
 
-            git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}.git ${{ inputs.soc }}
+            git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}.git ${{ inputs.soc }} || exit 1
 
             if [[ "${{ inputs.has_modules_repo }}" == "true" ]]; then
 
-                git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}-modules.git ${{ inputs.soc }}-modules
+                git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}-modules.git ${{ inputs.soc }}-modules || exit 1
 
             fi
 
@@ -252,7 +262,7 @@ jobs:
 
           mkdir -p toolchains/${{ inputs.clang_version }}
           
-          tar -xf "${{ inputs.clang_version }}.tar.gz" -C "toolchains/${{ inputs.clang_version }}"
+          tar -xf "${{ inputs.clang_version }}.tar.gz" -C "toolchains/${{ inputs.clang_version }}" || exit 1
 
           if [[ "${{ inputs.enable_gcc_32bits }}" == "true" ]]; then
 
@@ -263,9 +273,9 @@ jobs:
           fi
 
 
-      - name: include ksu and susfs
+      - name: Include goodies
         run: |
-          cd ${{ inputs.soc }}
+          cd ${{ inputs.soc }} || exit 1
 
           case "${{ inputs.ksu_type }}" in
 
@@ -273,23 +283,23 @@ jobs:
               ;;
 
             "Official-KernelSU")
-              curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
+              curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main || exit 1
               ;;
 
             "KowSU")
-               curl -LSs "https://raw.githubusercontent.com/KOWX712/KernelSU/main/kernel/setup.sh" | bash -s master
+              curl -LSs "https://raw.githubusercontent.com/KOWX712/KernelSU/main/kernel/setup.sh" | bash -s master || exit 1
               ;;
 
             "KernelSU-by-xx")
-              curl -LSs "https://raw.githubusercontent.com/backslashxx/KernelSU/refs/heads/master/kernel/setup.sh" | bash -s master
+              curl -LSs "https://raw.githubusercontent.com/backslashxx/KernelSU/refs/heads/master/kernel/setup.sh" | bash -s master || exit 1
               ;;
 
             "KernelSU-Next")
-              curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s dev
+              curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s dev || exit 1
               ;;
 
             "KernelSU-Next-with-susfs")
-              curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/dev-susfs/kernel/setup.sh" | bash -s dev-susfs
+              curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/dev-susfs/kernel/setup.sh" | bash -s dev-susfs || exit 1
               ;;
 
             "ReSukiSU"|"ReSukiSU-with-susfs")
@@ -297,6 +307,148 @@ jobs:
               ;;
 
           esac
+
+          if [[ "${{ inputs.droidspaces }}" == "5.4-6.6" ]]; then
+
+            curl -Lo droidspaces.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/GKI/below-kernel-6.12/001.GKI-below-6.12-fix_sysvipc_kabi_6_7_8.patch
+            patch -p1 < droidspaces.patch
+
+            cat > arch/arm64/configs/vendor/droidspaces.config << EOF
+            # Kernel configurations for full DroidSpaces support for GKI
+            # Copyright (C) 2026 ravindu644 <droidcasts@protonmail.com>
+
+            # IPC
+            CONFIG_SYSVIPC=y
+            CONFIG_POSIX_MQUEUE=y
+
+            # Namespaces
+            CONFIG_IPC_NS=y
+            CONFIG_PID_NS=y
+
+            # HW Access Support
+            CONFIG_DEVTMPFS=y
+
+            # --- Below configs are optional but recommended ---
+
+            # Networking (Docker/NAT support)
+            CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
+
+            # UFW support
+            CONFIG_NETFILTER_XT_TARGET_REJECT=y
+            CONFIG_NETFILTER_XT_TARGET_LOG=y
+            CONFIG_NETFILTER_XT_MATCH_RECENT=y
+
+            # Fail2ban support
+            CONFIG_IP_SET=y
+            CONFIG_IP_SET_HASH_IP=y
+            CONFIG_IP_SET_HASH_NET=y
+            CONFIG_NETFILTER_XT_SET=y
+            EOF
+
+          elif [[ "${{ inputs.droidspaces }}" == "3.18-4.19" ]]; then
+
+            # Why there is no 01.fix_kernel_panic_in_xt_qtaguid.patch? Because I cant find net/netfilter/xt_qtaguid.c in my k4.14 4.19 5.4
+            # 为什么没有01.fix_kernel_panic_in_xt_qtaguid.patch? 在我用的4.14 4.19 5.4内无此文件
+
+            curl -Lo patch2.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/non-GKI/02.fix_restore%20cgroup%20file%20prefix%20handling%20.patch || exit 1
+            patch -p1 < patch2.patch
+
+            cat > arch/arm64/configs/vendor/droidspaces.config << EOF
+            # Kernel configurations for full DroidSpaces support
+            # Copyright (C) 2026 ravindu644 <droidcasts@protonmail.com>
+
+            # IPC mechanisms
+            CONFIG_SYSCTL=y
+            CONFIG_SYSVIPC=y
+            CONFIG_POSIX_MQUEUE=y
+
+            # Core namespace support
+            CONFIG_NAMESPACES=y
+            CONFIG_PID_NS=y
+            CONFIG_UTS_NS=y
+            CONFIG_IPC_NS=y
+
+            # Seccomp support
+            CONFIG_SECCOMP=y
+            CONFIG_SECCOMP_FILTER=y
+
+            # Control groups support
+            CONFIG_CGROUPS=y
+            CONFIG_CGROUP_DEVICE=y
+            CONFIG_CGROUP_PIDS=y
+            CONFIG_MEMCG=y
+            CONFIG_CGROUP_SCHED=y
+            CONFIG_FAIR_GROUP_SCHED=y
+            CONFIG_CGROUP_FREEZER=y
+            CONFIG_CGROUP_NET_PRIO=y
+
+            # Device filesystem support
+            CONFIG_DEVTMPFS=y
+
+            # Overlay filesystem support (required for volatile mode)
+            CONFIG_OVERLAY_FS=y
+
+            # Firmware loading support
+            CONFIG_FW_LOADER=y
+            CONFIG_FW_LOADER_USER_HELPER=y
+            CONFIG_FW_LOADER_COMPRESS=y
+
+            # Droidspaces Network Isolation Support - NAT/none modes
+            CONFIG_NET_NS=y
+            CONFIG_VETH=y
+            CONFIG_BRIDGE=y
+            CONFIG_NETFILTER=y
+            CONFIG_BRIDGE_NETFILTER=y
+            CONFIG_NETFILTER_ADVANCED=y
+            CONFIG_NF_CONNTRACK=y
+            CONFIG_IP_NF_IPTABLES=y
+            CONFIG_IP_NF_FILTER=y
+            CONFIG_NF_NAT=y
+            CONFIG_NF_TABLES=y
+            CONFIG_IP_NF_TARGET_MASQUERADE=y
+            CONFIG_NETFILTER_XT_TARGET_MASQUERADE=y
+            CONFIG_NETFILTER_XT_TARGET_TCPMSS=y
+            CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
+            CONFIG_NF_CONNTRACK_NETLINK=y
+            CONFIG_NF_NAT_REDIRECT=y
+            CONFIG_IP_ADVANCED_ROUTER=y
+            CONFIG_IP_MULTIPLE_TABLES=y
+
+            # legacy compat
+            CONFIG_NF_CONNTRACK_IPV4=y
+            CONFIG_NF_NAT_IPV4=y
+            CONFIG_IP_NF_NAT=y
+
+            # Disable this on older kernels to make internet work
+            CONFIG_ANDROID_PARANOID_NETWORK=n
+
+            # UFW & FAIL2BAN CORE
+            CONFIG_NETFILTER_XT_MATCH_COMMENT=y
+            CONFIG_NETFILTER_XT_MATCH_STATE=y
+            CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y
+            CONFIG_NETFILTER_XT_MATCH_MULTIPORT=y
+            CONFIG_NETFILTER_XT_MATCH_HL=y
+            CONFIG_NETFILTER_XT_TARGET_REJECT=y
+            CONFIG_IP_NF_TARGET_REJECT=y
+            CONFIG_NETFILTER_XT_TARGET_LOG=y
+            CONFIG_IP_NF_TARGET_ULOG=y
+            CONFIG_NETFILTER_XT_MATCH_RECENT=y
+            CONFIG_NETFILTER_XT_MATCH_LIMIT=y
+            CONFIG_NETFILTER_XT_MATCH_HASHLIMIT=y
+            CONFIG_NETFILTER_XT_MATCH_OWNER=y
+            CONFIG_NETFILTER_XT_MATCH_PKTTYPE=y
+            CONFIG_NETFILTER_XT_MATCH_MARK=y
+            CONFIG_NETFILTER_XT_TARGET_MARK=y
+            CONFIG_IP_SET=y
+            CONFIG_IP_SET_HASH_IP=y
+            CONFIG_IP_SET_HASH_NET=y
+            CONFIG_NETFILTER_XT_SET=y
+            CONFIG_NETFILTER_NETLINK_QUEUE=y
+            CONFIG_NETFILTER_NETLINK_LOG=y
+            CONFIG_NETFILTER_XT_TARGET_NFLOG=y
+            EOF
+
+          fi
 
           if [[ "${{ inputs.ksu_type }}" == *susfs* ]]; then
 
@@ -311,19 +463,19 @@ jobs:
 
             elif [[ "${{ inputs.susfs-gki }}" != "None" ]]; then
 
-              git clone -b gki-${{ inputs.susfs-gki }} https://gitlab.com/simonpunk/susfs4ksu.git susfs
-              cd susfs
+              git clone -b gki-${{ inputs.susfs-gki }} https://gitlab.com/simonpunk/susfs4ksu.git susfs || exit 1
+              cd susfs || exit 1
               cp ./kernel_patches/50_add_susfs_in_gki-${{ inputs.susfs-gki }}.patch ..
               cp ./kernel_patches/fs/* ../fs/
               cp ./kernel_patches/include/linux/* ../include/linux/
-              cd ..
+              cd .. || exit 1
 
               patch -p1 < 50_add_susfs_in_gki-${{ inputs.susfs-gki }}.patch
 
             elif [[ "${{ inputs.susfs-nongki }}" != "None" ]]; then
 
-              curl -Lo susfs.patch https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/Patch/susfs_patch_to_${{ inputs.susfs-nongki }}.patch
-              curl -Lo inline.sh https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/susfs_inline_hook_patches.sh
+              curl -Lo susfs.patch https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/Patch/susfs_patch_to_${{ inputs.susfs-nongki }}.patch || exit 1
+              curl -Lo inline.sh https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/susfs_inline_hook_patches.sh || exit 1
 
               patch -p1 < susfs.patch
               bash inline.sh
@@ -355,7 +507,14 @@ jobs:
           
           fi
           
-          cd ${{ inputs.soc }}
+          if [[ "${{ inputs.droidspaces }}" != "None" ]]; then
+            export DROIDSPACES_CONFIG="vendor/droidspaces.config"
+          else
+            export DROIDSPACES_CONFIG=""
+          fi
+
+
+          cd ${{ inputs.soc }} || exit 1
 
           if [[ "${{ inputs.kernel_configs }}" == "Manual-Type" ]]; then
 
@@ -373,27 +532,27 @@ jobs:
             case "${{ inputs.kernel_configs }}" in
 
               "oplus-sm8150-los")
-              make O=out vendor/sm8150-perf_defconfig vendor/oplus.config
+              make O=out vendor/sm8150-perf_defconfig vendor/oplus.config $DROIDSPACES_CONFIG
               ;;
 
               "oplus-sm8150-yaap")
-              make O=out gulch_defconfig vendor/debugfs.config
+              make O=out gulch_defconfig vendor/debugfs.config $DROIDSPACES_CONFIG
               ;;
 
               "oplus-sm8250-los")
-              make O=out vendor/kona-perf_defconfig vendor/oplus.config
+              make O=out vendor/kona-perf_defconfig vendor/oplus.config $DROIDSPACES_CONFIG
               ;;
 
               "oplus-sm8350-los")
-              make O=out vendor/lahaina-qgki_defconfig
+              make O=out vendor/lahaina-qgki_defconfig $DROIDSPACES_CONFIG
               ;;
 
               "oplus-sm8550-los")
-              make O=out gki_defconfig vendor/kalama_GKI.config vendor/oplus/kalama_GKI.config vendor/debugfs.config
+              make O=out gki_defconfig vendor/kalama_GKI.config vendor/oplus/kalama_GKI.config vendor/debugfs.config $DROIDSPACES_CONFIG
               ;;
 
               "oplus-sm8650-los")
-              make O=out gki_defconfig vendor/pineapple_GKI.config vendor/oplus/pineapple_GKI.config
+              make O=out gki_defconfig vendor/pineapple_GKI.config vendor/oplus/pineapple_GKI.config $DROIDSPACES_CONFIG
               ;;
 
             esac
@@ -465,18 +624,18 @@ jobs:
           
           fi
 
-          cd ${{ inputs.soc }}
+          cd ${{ inputs.soc }} || exit 1
 
           make -j$(nproc) O=out Image
 
       - name: Make AnyKernel3
         run: |
           ZIP_NAME="${{ inputs.soc }}_${{ inputs.kernel_source }}-${{ inputs.kernel_branch }}_${{ inputs.ksu_type }}_$(date -u +"%Y%m%d_%H%M")"
-          git clone https://github.com/Kernel-SU/AnyKernel3.git
+          git clone https://github.com/Kernel-SU/AnyKernel3.git || exit 1
 
           cp ${{ inputs.soc }}/out/arch/arm64/boot/Image AnyKernel3/Image
           cp ${{ inputs.soc }}/out/arch/arm64/boot/Image ./Image
-          cd AnyKernel3
+          cd AnyKernel3 || exit 1
 
           sed -i "s|ksu_supported=false|ksu_supported=true|" anykernel.sh
 
@@ -485,6 +644,6 @@ jobs:
       - name: Create GitHub Release
         run: |
           REL_NAME="${{ inputs.soc }}_${{ inputs.kernel_source }}-${{ inputs.kernel_branch }}_${{ inputs.ksu_type }}_$(date -u +"%Y%m%d_%H%M")"
-          cd ${GITHUB_WORKSPACE}
+          cd ${GITHUB_WORKSPACE} || exit 1
           ZIP_FILE=$(ls *.zip)
           gh release create "$REL_NAME" --title "$REL_NAME" --notes "" "${ZIP_FILE}" Image
